const KEY='ofertaCertaV16Products',OLD=['ofertaCertaV15Products','ofertaCertaV14Products'],$=id=>document.getElementById(id);
const ids=['productForm','productId','title','price','oldPrice','category','badge','description','featured','mercadoLivreLink','mercadoLivrePrice','shopeeLink','shopeePrice','amazonLink','amazonPrice','tiktokLink','tiktokPrice','imageFiles','imagesPreview','previewImage','previewTitle','previewPrice','previewOldPrice','previewCategory','previewBadge','previewStores','adminProductsList','totalProducts','totalFeatured','totalClicks','cancelEditBtn','resetBtn','formTitle','saveBtn'];ids.forEach(id=>window[id]=$(id));
let imgs=[],cover=0,busy=false;
function norm(p){let images=Array.isArray(p.images)&&p.images.length?p.images:(p.image?[p.image]:[]),stores=p.stores||{};if(!Object.keys(stores).length&&p.affiliateLink)stores={mercadoLivre:{name:'Mercado Livre',link:p.affiliateLink,price:p.price,clicks:p.clicks||0}};return {...p,images,image:p.image||images[0]||'',stores};}
function get(){try{let raw=localStorage.getItem(KEY);if(!raw)for(const k of OLD){raw=localStorage.getItem(k);if(raw){localStorage.setItem(KEY,raw);break;}}let d=JSON.parse(raw||'[]');return Array.isArray(d)?d.map(norm):[];}catch{return[];}}
function save(d){try{localStorage.setItem(KEY,JSON.stringify(d));return true}catch{alert('Armazenamento cheio. Use menos fotos ou exclua produtos antigos.');return false}}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function stores(){return {mercadoLivre:{name:'Mercado Livre',link:mercadoLivreLink.value.trim(),price:+mercadoLivrePrice.value||null,clicks:0},shopee:{name:'Shopee',link:shopeeLink.value.trim(),price:+shopeePrice.value||null,clicks:0},amazon:{name:'Amazon',link:amazonLink.value.trim(),price:+amazonPrice.value||null,clicks:0},tiktok:{name:'TikTok Shop',link:tiktokLink.value.trim(),price:+tiktokPrice.value||null,clicks:0}}}
function preview(){previewTitle.textContent=title.value||'Título do produto';previewPrice.textContent=money(price.value);previewCategory.textContent=category.value||'Categoria';previewImage.src=imgs[cover]||'https://placehold.co/800x800?text=Foto+do+produto';oldPrice.value?(previewOldPrice.textContent=money(oldPrice.value),previewOldPrice.classList.remove('hidden')):previewOldPrice.classList.add('hidden');badge.value?(previewBadge.textContent=badge.value,previewBadge.classList.remove('hidden')):previewBadge.classList.add('hidden');let a=Object.entries(stores()).filter(([,s])=>s.link);previewStores.innerHTML=a.length?a.map(([k,s])=>`<span class="store-button store-${k==='mercadoLivre'?'ml':k}"><span>${s.name}</span><span>${s.price?money(s.price):'Comprar'}</span></span>`).join(''):'<span class="preview-hint">Os botões aparecerão aqui.</span>'}
function renderImgs(){imagesPreview.innerHTML=imgs.length?imgs.map((src,i)=>`<div class="image-preview-item ${i===cover?'cover':''}">${i===cover?'<span class="cover-label">CAPA</span>':''}<img src="${src}"><div class="image-preview-actions"><button type="button" class="set-cover-button" data-a="cover" data-i="${i}">${i===cover?'Capa atual':'Usar capa'}</button><button type="button" class="remove-image-button" data-a="remove" data-i="${i}">Excluir</button></div></div>`).join(''):'<div class="images-empty">Nenhuma foto selecionada.</div>';preview()}
function reset(){productForm.reset();productId.value='';imgs=[];cover=0;saveBtn.textContent='Publicar produto';saveBtn.disabled=false;formTitle.textContent='Cadastrar produto';cancelEditBtn.classList.add('hidden');renderImgs()}
function render(){let p=get();totalProducts.textContent=p.length;totalFeatured.textContent=p.filter(x=>x.featured).length;totalClicks.textContent=p.reduce((n,x)=>n+Object.values(x.stores||{}).reduce((a,s)=>a+(+s.clicks||0),0),0);adminProductsList.innerHTML=p.length?p.map(x=>`<article class="admin-product-item"><img src="${esc(x.image||'https://placehold.co/300x300?text=Sem+foto')}"><div><h3>${esc(x.title)}</h3><p>${esc(x.category)} • ${Object.values(x.stores||{}).filter(s=>s.link).map(s=>s.name).join(', ')}</p></div><div class="item-actions"><button class="mini-btn" data-act="edit" data-id="${x.id}">Editar</button><button class="mini-btn danger" data-act="delete" data-id="${x.id}">Excluir</button></div></article>`).join(''):'<div class="empty-state"><h3>Nenhum produto cadastrado</h3></div>'}
function edit(id){let p=get().find(x=>x.id===id);if(!p)return;productId.value=p.id;title.value=p.title;price.value=p.price;oldPrice.value=p.oldPrice||'';category.value=p.category;badge.value=p.badge||'';description.value=p.description||'';featured.checked=!!p.featured;for(const [k,s] of Object.entries(p.stores||{})){let pre=k==='mercadoLivre'?'mercadoLivre':k;$(pre+'Link').value=s.link||'';$(pre+'Price').value=s.price||''}imgs=[...p.images];cover=Math.max(0,imgs.indexOf(p.image));formTitle.textContent='Editar produto';saveBtn.textContent='Salvar alterações';cancelEditBtn.classList.remove('hidden');renderImgs();scrollTo({top:0,behavior:'smooth'})}
function read(f){return new Promise((r,j)=>{let x=new FileReader;x.onload=()=>r(x.result);x.onerror=j;x.readAsDataURL(f)})}function load(s){return new Promise((r,j)=>{let i=new Image;i.onload=()=>r(i);i.onerror=j;i.src=s})}async function compress(f){let s=await read(f),i=await load(s),w=i.naturalWidth,h=i.naturalHeight,z=Math.min(1,900/Math.max(w,h));w*=z;h*=z;let c=document.createElement('canvas');c.width=w;c.height=h;let x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,w,h);x.drawImage(i,0,0,w,h);return c.toDataURL('image/jpeg',.68)}
imageFiles.onchange=async e=>{let fs=[...e.target.files].slice(0,5-imgs.length);if(!fs.length)return;busy=true;saveBtn.disabled=true;for(let i=0;i<fs.length;i++){saveBtn.textContent=`Processando ${i+1}/${fs.length}`;imgs.push(await compress(fs[i]))}busy=false;saveBtn.disabled=false;saveBtn.textContent=productId.value?'Salvar alterações':'Publicar produto';imageFiles.value='';renderImgs()};
imagesPreview.onclick=e=>{let b=e.target.closest('[data-a]');if(!b)return;let i=+b.dataset.i;if(b.dataset.a==='cover')cover=i;else{imgs.splice(i,1);if(cover>=imgs.length)cover=Math.max(0,imgs.length-1)}renderImgs()};
[title,price,oldPrice,category,badge,mercadoLivreLink,mercadoLivrePrice,shopeeLink,shopeePrice,amazonLink,amazonPrice,tiktokLink,tiktokPrice].forEach(x=>x.oninput=preview);
productForm.onsubmit=e=>{e.preventDefault();if(busy)return;let st=stores(),active=Object.values(st).filter(s=>s.link);if(!active.length)return alert('Cadastre pelo menos um link de loja.');if(active.some(s=>{try{return new URL(s.link).protocol!=='https:'}catch{return true}}))return alert('Existe um link inválido.');if(!imgs.length)return alert('Selecione uma foto.');let all=get(),id=productId.value,old=all.find(x=>x.id===id),ordered=[...imgs];if(cover>0)ordered.unshift(ordered.splice(cover,1)[0]);for(const k in st)st[k].clicks=old?.stores?.[k]?.clicks||0;let p={id:id||(crypto.randomUUID?crypto.randomUUID():Date.now()+''),title:title.value.trim(),price:+price.value,oldPrice:+oldPrice.value||null,category:category.value,badge:badge.value,description:description.value.trim(),stores:st,images:ordered,image:ordered[0],featured:featured.checked};if(id){let i=all.findIndex(x=>x.id===id);all[i]=p}else all.unshift(p);if(save(all)){render();reset();alert(id?'Produto atualizado.':'Produto publicado.')}};
adminProductsList.onclick=e=>{let b=e.target.closest('[data-act]');if(!b)return;if(b.dataset.act==='edit')edit(b.dataset.id);else if(confirm('Excluir este produto?')){save(get().filter(x=>x.id!==b.dataset.id));render()}};resetBtn.onclick=reset;cancelEditBtn.onclick=reset;render();renderImgs();
